version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    reviewers:
      - vkoop
    assignees:
      - vkoop
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    reviewers:
      - vkoop
    assignees:
      - vkoop
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    reviewers:
      - vkoop
    assignees:
      - vkoop
